---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: default
spec:
  containers:
  - image: alpine
    command:
      - /bin/sh
      - "-c"
      - "sleep infinity"
    imagePullPolicy: IfNotPresent
    name: alpine
  #   volumeMounts:
  #   - mountPath: /cache
  #     name: cache-volume
  # volumes:
  # - name: cache-volume
  #   emptyDir:
  #     sizeLimit: 200Gi
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 1.1.1.1 # this is an example
    searches:
      - default.svc.cluster.local
      - svc.cluster.local
      - cluster.local
    options:
      - name: ndots
        value: "5"
  nodeSelector:
    kubernetes.io/hostname: poc-md-1-56v7p-kfq55 
  restartPolicy: Always

#
# apk add fio --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
# fio --name=file_test --direct=1 --rw=randread --bs=4k --ioengine=libaio --iodepth=256 --runtime=120 --numjobs=4 --time_based --group_reporting --size=20G --runtime=300s --time_based --output=fio_output.log --filename=/tmp.test
#